### ISSUE TITLE
[FEATURE REQUEST]: Ability to install bleeding edge Ax and BoTorch together as package deps

### ISSUE THREAD

**Issue by CompRhys** [facebook/Ax#3430]
### Motivation

I have a package that we've built internally that points to the bleeding edge of our forks of Ax and BoTorch using:
```
    "ax-platform @ git+https://github.com/Radical-AI/Ax.git@main",
    "botorch @ git+https://github.com/Radical-AI/botorch.git@main",
```

Having set `export ALLOW_BOTORCH_LATEST=true` doesn't work in this instance and I get the following error:
```
The conflict is caused by:
    radical-package 0.1.0 depends on botorch 0.1.dev2129+g78c04e2 (from git+https://github.com/Radical-AI/botorch.git@main)
    ax-platform 0.1.dev3838 depends on botorch>=0.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

### Describe the solution you'd like to see implemented in Ax.

rework the pinning such that pinning on the package is by default allowing latest and then hard pinned during the package release process.

### Is this related to an existing issue in Ax or another repository? If so please include links to those Issues here.

https://github.com/astral-sh/uv/issues/11816

### Code of Conduct

- [x] I agree to follow Ax's Code of Conduct

**Comment by Balandat** [comment]
> Having set export ALLOW_BOTORCH_LATEST=true doesn't work in this instance 

This is b/c this happens during dependency resolution rather than at installation time, right? I saw the uv issue you linked, ideally there would be a way to support this but it seems that this might not be straightforward. 

> rework the pinning such that pinning on the package is by default allowing latest and then hard pinned during the package release process.

So you mean basically right before a release we'd manually commit the pin and then remove it again once the release is out? This adds some overhead to the release process but could be reasonable if it helps avoid issues with dependency resolution more broadly (I know that using an env var in setup.py also doesn't work with non-setuptools package install methods).

**Comment by CompRhys** [comment]
> So you mean basically right before a release we'd manually commit the pin and then remove it again once the release is out? This adds some overhead to the release process but could be reasonable if it helps avoid issues with dependency resolution more broadly (I know that using an env var in setup.py also doesn't work with non-setuptools package install methods).

I'm not sure where you build for pypi etc but I would think that if you swapped the default in the `setup.py` then all you would need to do is have a line of code in the build script that exports the alternative variable? I agree that manually having to change things wouldn't be a good solution. If you're pulling the code to install rather than from pypi then I think that it's not out of scope to imagine that those same people may also tinker in botorch which and so the uncapped pin would be a sensible default

**Comment by Balandat** [comment]
> then all you would need to do is have a line of code in the build script that exports the alternative variable?

I don't think this would work (at least IIUC what you mean), since the released code would still not be pinned? Unless we do something sort of hacky where we actually auto-edit the `setup.py` file during the build process to add the pin and only ever use that in the release itself (which means that the code of the release technically isn't tied to a specific commit, which is awkward).

**Comment by CompRhys** [comment]
> > then all you would need to do is have a line of code in the build script that exports the alternative variable?
> 
> I don't think this would work (at least IIUC what you mean), since the released code would still not be pinned? Unless we do something sort of hacky where we actually auto-edit the `setup.py` file during the build process to add the pin and only ever use that in the release itself (which means that the code of the release technically isn't tied to a specific commit, which is awkward).

what I loosely was thinking is something like changing this code as follows

```python
PINNED_BOTORCH_VERSION = "0.13.0"

if os.environ.get("ALLOW_BOTORCH_LATEST"):
    # allows a more recent previously installed version of botorch to remain
    # if there is no previously installed version, installs the latest release
    botorch_req = f"botorch>={PINNED_BOTORCH_VERSION}"
else:
    botorch_req = f"botorch=={PINNED_BOTORCH_VERSION}"
```

```python
PINNED_BOTORCH_VERSION = "0.13.0"

if os.environ.get("PIN_BOTORCH_VERSION"):
    botorch_req = f"botorch=={PINNED_BOTORCH_VERSION}"
else:
    # allows a more recent previously installed version of botorch to remain
    # if there is no previously installed version, installs the latest release
    botorch_req = f"botorch>={PINNED_BOTORCH_VERSION}"
```

then on the build machine for making the pip wheel you just set the `PIN_BOTORCH_VERSION` variable?

I may be missing something obvious here but I don't think the code needs to be edited each time?

**Comment by Balandat** [comment]
The issue I see with this is that if we release a new botorch version, then if someone installs an oder Ax version (either b/c we haven't released a new one or b/c the user requests a specific version) that is not compatible with the changes in the newest botorch release, then this will install fine via the package manager but then error out at runtime b/c of this incompatibility. Does this make sense (I may be missing something here)?

**Comment by CompRhys** [comment]
I don't believe that the pypi wheels would be different to how they are now if this was inverted with the correct release code.

Currently say if I do `pip install ax-platform==0.4` which a bleeding edge botorch installed in editable mode because the wheel pins its deps to `botorch==0.11` it will downgrade me. The intended user only using official releases will still get the correct dependency solving because the wheel on pypi would still assert that the pin was needed. 

My interest is that for people who want to mess with the code I can make a fork of both packages and then point to them in my requirements or `pyproject.toml` and the default will be that because I am installing from code and adding things that could break things I have assumed the agency over making sure that things work. 

I am in full agreement that if it's not possible to make a change without ensuring that there's no change in what happens to the intended user downloading from a package manager that nothing should change to indulge minority use cases. I have no idea on how releases work at Meta but as a mock up for gh actions something like the following in combination with the change to the logic above would both ensure that the releases are exactly as they are now but also give a more liberal default for people using the source code therefore avoiding the issues I was having with uv/pip and git+url installs of bleeding edge.

```
name: Build and Publish Python Package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel

      - name: Build package with pinned botorch
        env:
          PIN_BOTORCH_VERSION: "true"  # Setting the environment variable to pin botorch version
        run: |
          python -m build
          
      - name: Check distribution
        run: |
          python -m twine check dist/*
          
      - name: Publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          
      - name: Publish to TestPyPI (for non-release)
        if: github.event_name != 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
```
